name: Azure Login test
on: workflow_dispatch
jobs:
  AzureLogin:
    runs-on: ubuntu-latest
    steps:
      
      - name: Azure action
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURESECRET }}'
      
      - name: Azure Powershell action
        uses: Azure/powershell@v1
        with:
          inlineScript: Get-AzResourceGroup -Name hemievents
          azPSVersion: "latest"

      - name: Azure CLI action
        uses: azure/CLI@v1
        with: 
          azcliversion: 2.0.72
          inlineScript: |
            az account show
            az storage -h


        
